import os
from datetime import datetime
from config import BASE_PATH
from database.db_operation import ImageTeaDB


class PhotoshopJSXGenerator:
    def __init__(self):
        self.db = ImageTeaDB()
        self.jsx_dir = os.path.join(BASE_PATH, 'temp', 'jsx', 'photoshop')
        os.makedirs(self.jsx_dir, exist_ok=True)
    
    def generate_jsx(self, preset_id, source_files, output_path, config, is_single_run_with_file=False):
        """Generate JSX file untuk Photoshop
        
        Args:
            preset_id: ID preset dari database
            source_files: List file paths untuk diproses (bisa empty untuk single run)
            output_path: Path output folder
            config: Dict config (prefix, suffix, dll)
            is_single_run_with_file: True if single run mode with loaded file
        
        Returns:
            str: Path ke generated JSX file
        """
        preset_steps = self.db.get_preset_steps(preset_id)
        
        is_batch = len(source_files) > 0 and not is_single_run_with_file
        
        jsx_code = self._generate_jsx_code(preset_steps, source_files, output_path, config, is_batch, is_single_run_with_file)
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        jsx_filename = f"preset_{preset_id}_{timestamp}.jsx"
        jsx_path = os.path.join(self.jsx_dir, jsx_filename)
        
        with open(jsx_path, 'w', encoding='utf-8') as f:
            f.write(jsx_code)
        
        print(f"Generated JSX: {jsx_path}")
        return jsx_path
    
    def _generate_jsx_code(self, preset_steps, source_files, output_path, config, is_batch, is_single_run_with_file):
        """Generate JSX code content"""
        
        jsx = []
        jsx.append("// Generated by Image Tea - Action Sequencer")
        jsx.append(f"// Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        jsx.append("")
        
        jsx.append("// Configuration")
        jsx.append("var config = {")
        jsx.append(f"    outputPath: '{output_path.replace(chr(92), '/')}',")
        jsx.append(f"    prefix: '{config.get('output_prefix', '')}',")
        jsx.append(f"    suffix: '{config.get('output_suffix', '')}',")
        jsx.append(f"    isBatch: {str(is_batch).lower()},")
        jsx.append(f"    isSingleRunWithFile: {str(is_single_run_with_file).lower()}")
        jsx.append("};")
        jsx.append("")
        
        if is_batch or is_single_run_with_file:
            jsx.append("// Source files")
            jsx.append("var sourceFiles = [")
            for sf in source_files:
                jsx.append(f"    '{sf.replace(chr(92), '/')}',")
            jsx.append("];")
            jsx.append("")
        
        export_steps = [s for s in preset_steps if self.db.get_action_by_id(s['action_id']).get('type') == 'Export']
        non_export_steps = [s for s in preset_steps if self.db.get_action_by_id(s['action_id']).get('type') != 'Export']
        
        jsx.append("// Main execution")
        jsx.append("try {")
        
        if is_batch:
            jsx.append("    for (var i = 0; i < sourceFiles.length; i++) {")
            jsx.append("        var doc = app.open(new File(sourceFiles[i]));")
            jsx.append("")
            
            for step in non_export_steps:
                action_detail = self.db.get_action_by_id(step['action_id'])
                if action_detail:
                    jsx.append(f"        // Step {step['order_index']}: {step['name']}")
                    
                    action_type = action_detail.get('type', 'Action')
                    
                    if action_type == 'Action':
                        jsx.append(f"        app.doAction('{action_detail['name']}', '{step['action_set']}');")
                    elif action_type == 'Delay':
                        delay_ms = action_detail.get('delay', 0)
                        if delay_ms > 0:
                            jsx.append(f"        $.sleep({delay_ms});")
                    elif action_type == 'Script':
                        js_code = action_detail.get('javascript_code', '').strip()
                        if js_code:
                            for line in js_code.split('\n'):
                                jsx.append(f"        {line}")
                        delay_ms = action_detail.get('delay', 0)
                        if delay_ms > 0:
                            jsx.append(f"        $.sleep({delay_ms});")
                    
                    jsx.append("")
            
            if export_steps:
                for step in export_steps:
                    action_detail = self.db.get_action_by_id(step['action_id'])
                    if action_detail:
                        export_format = action_detail.get('export_format', 'PNG').upper()
                        jsx.append(f"        // Export: {action_detail['name']}")
                        jsx.append(self._generate_export_code(export_format, "        "))
                        jsx.append("")
            
            jsx.append("        doc.close(SaveOptions.DONOTSAVECHANGES);")
            jsx.append("    }")
        elif is_single_run_with_file:
            jsx.append("    if (sourceFiles.length > 0) {")
            jsx.append("        var doc = app.open(new File(sourceFiles[0]));")
            jsx.append("    }")
            jsx.append("")
            
            for step in non_export_steps:
                action_detail = self.db.get_action_by_id(step['action_id'])
                if action_detail:
                    jsx.append(f"    // Step {step['order_index']}: {step['name']}")
                    
                    action_type = action_detail.get('type', 'Action')
                    
                    if action_type == 'Action':
                        jsx.append(f"    app.doAction('{action_detail['name']}', '{step['action_set']}');")
                    elif action_type == 'Delay':
                        delay_ms = action_detail.get('delay', 0)
                        if delay_ms > 0:
                            jsx.append(f"    $.sleep({delay_ms});")
                    elif action_type == 'Script':
                        js_code = action_detail.get('javascript_code', '').strip()
                        if js_code:
                            for line in js_code.split('\n'):
                                jsx.append(f"    {line}")
                        delay_ms = action_detail.get('delay', 0)
                        if delay_ms > 0:
                            jsx.append(f"    $.sleep({delay_ms});")
                    
                    jsx.append("")
            
            if export_steps:
                for step in export_steps:
                    action_detail = self.db.get_action_by_id(step['action_id'])
                    if action_detail:
                        export_format = action_detail.get('export_format', 'PNG').upper()
                        jsx.append(f"    // Export: {action_detail['name']}")
                        jsx.append(self._generate_export_code(export_format, "    "))
                        jsx.append("")
            # If a source file was opened for single-run, close it after processing
            jsx.append("    if (sourceFiles.length > 0) {")
            jsx.append("        doc.close(SaveOptions.DONOTSAVECHANGES);")
            jsx.append("    }")
        else:
            # Single-run without an explicit source files list: use the currently active document
            jsx.append("    if (app.documents.length == 0) {")
            jsx.append("        alert('No open document found for single-run without source. Please open or select a document.');")
            jsx.append("    } else {")
            jsx.append("        var doc = app.activeDocument;")
            jsx.append("")
            for step in non_export_steps:
                action_detail = self.db.get_action_by_id(step['action_id'])
                if action_detail:
                    jsx.append(f"        // Step {step['order_index']}: {step['name']}")
                    
                    action_type = action_detail.get('type', 'Action')
                    
                    if action_type == 'Action':
                        jsx.append(f"        app.doAction('{action_detail['name']}', '{step['action_set']}');")
                    elif action_type == 'Delay':
                        delay_ms = action_detail.get('delay', 0)
                        if delay_ms > 0:
                            jsx.append(f"        $.sleep({delay_ms});")
                    elif action_type == 'Script':
                        js_code = action_detail.get('javascript_code', '').strip()
                        if js_code:
                            for line in js_code.split('\n'):
                                jsx.append(f"        {line}")
                        delay_ms = action_detail.get('delay', 0)
                        if delay_ms > 0:
                            jsx.append(f"        $.sleep({delay_ms});")
                    
                    jsx.append("")
            
            if export_steps:
                for step in export_steps:
                    action_detail = self.db.get_action_by_id(step['action_id'])
                    if action_detail:
                        export_format = action_detail.get('export_format', 'PNG').upper()
                        jsx.append(f"        // Export: {action_detail['name']}")
                        jsx.append(self._generate_export_code(export_format, "        "))
                        jsx.append("")
            # close the active document context
            jsx.append("    }")
        
        jsx.append("} catch(e) {")
        jsx.append("    alert('Error: ' + e.message);")
        jsx.append("}")
        
        return "\n".join(jsx)
    
    def _generate_export_code(self, export_format, indent):
        """Generate export code for Photoshop"""
        code_lines = []
        
        if export_format == 'PNG':
            code_lines.append(f"{indent}var pngOptions = new ExportOptionsSaveForWeb();")
            code_lines.append(f"{indent}pngOptions.format = SaveDocumentType.PNG;")
            code_lines.append(f"{indent}pngOptions.PNG8 = false;")
            code_lines.append(f"{indent}var fileName = config.prefix + doc.name.replace(/\\.[^.]+$/, '') + config.suffix + '.png';")
            code_lines.append(f"{indent}var saveFile = new File(config.outputPath + '/' + fileName);")
            code_lines.append(f"{indent}doc.exportDocument(saveFile, ExportType.SAVEFORWEB, pngOptions);")
        elif export_format == 'JPG' or export_format == 'JPEG':
            code_lines.append(f"{indent}var jpgOptions = new JPEGSaveOptions();")
            code_lines.append(f"{indent}jpgOptions.quality = 12;")
            code_lines.append(f"{indent}var fileName = config.prefix + doc.name.replace(/\\.[^.]+$/, '') + config.suffix + '.jpg';")
            code_lines.append(f"{indent}var saveFile = new File(config.outputPath + '/' + fileName);")
            code_lines.append(f"{indent}doc.saveAs(saveFile, jpgOptions, true);")
        elif export_format == 'PSD':
            code_lines.append(f"{indent}var psdOptions = new PhotoshopSaveOptions();")
            code_lines.append(f"{indent}psdOptions.embedColorProfile = true;")
            code_lines.append(f"{indent}var fileName = config.prefix + doc.name.replace(/\\.[^.]+$/, '') + config.suffix + '.psd';")
            code_lines.append(f"{indent}var saveFile = new File(config.outputPath + '/' + fileName);")
            code_lines.append(f"{indent}doc.saveAs(saveFile, psdOptions, true);")
        elif export_format == 'PDF':
            code_lines.append(f"{indent}var pdfOptions = new PDFSaveOptions();")
            code_lines.append(f"{indent}var fileName = config.prefix + doc.name.replace(/\\.[^.]+$/, '') + config.suffix + '.pdf';")
            code_lines.append(f"{indent}var saveFile = new File(config.outputPath + '/' + fileName);")
            code_lines.append(f"{indent}doc.saveAs(saveFile, pdfOptions, true);")
        elif export_format == 'TIFF':
            code_lines.append(f"{indent}var tiffOptions = new TiffSaveOptions();")
            code_lines.append(f"{indent}var fileName = config.prefix + doc.name.replace(/\\.[^.]+$/, '') + config.suffix + '.tif';")
            code_lines.append(f"{indent}var saveFile = new File(config.outputPath + '/' + fileName);")
            code_lines.append(f"{indent}doc.saveAs(saveFile, tiffOptions, true);")
        
        return "\n".join(code_lines)
